/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.FlowLayout;
import javax.swing.JFrame;

/**
 *
 * @author phamtuyetnga
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVoucher = new com.k33ptoo.components.KButton();
        btnKhachHang = new com.k33ptoo.components.KButton();
        btnSanPham = new com.k33ptoo.components.KButton();
        btnHoaDon = new com.k33ptoo.components.KButton();
        btnBanHang = new com.k33ptoo.components.KButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnVoucher1 = new com.k33ptoo.components.KButton();
        btnNhanVien = new com.k33ptoo.components.KButton();
        Panel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));

        btnVoucher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons-voucher.png"))); // NOI18N
        btnVoucher.setText("VOUCHER");
        btnVoucher.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnVoucher.setkBackGroundColor(new java.awt.Color(36, 47, 65));
        btnVoucher.setkEndColor(new java.awt.Color(36, 47, 65));
        btnVoucher.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        btnVoucher.setkHoverForeGround(new java.awt.Color(36, 47, 65));
        btnVoucher.setkHoverStartColor(new java.awt.Color(36, 47, 65));
        btnVoucher.setkPressedColor(new java.awt.Color(36, 47, 65));
        btnVoucher.setkSelectedColor(new java.awt.Color(36, 47, 65));
        btnVoucher.setkStartColor(new java.awt.Color(36, 47, 65));
        btnVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoucherActionPerformed(evt);
            }
        });

        btnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons-khachhang.png"))); // NOI18N
        btnKhachHang.setText("KHÁCH HÀNG");
        btnKhachHang.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnKhachHang.setkBackGroundColor(new java.awt.Color(36, 47, 65));
        btnKhachHang.setkEndColor(new java.awt.Color(36, 47, 65));
        btnKhachHang.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        btnKhachHang.setkHoverForeGround(new java.awt.Color(36, 47, 65));
        btnKhachHang.setkHoverStartColor(new java.awt.Color(36, 47, 65));
        btnKhachHang.setkPressedColor(new java.awt.Color(36, 47, 65));
        btnKhachHang.setkSelectedColor(new java.awt.Color(36, 47, 65));
        btnKhachHang.setkStartColor(new java.awt.Color(36, 47, 65));
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        btnSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons-sanpham.png"))); // NOI18N
        btnSanPham.setText("SẢN PHẨM");
        btnSanPham.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnSanPham.setkBackGroundColor(new java.awt.Color(36, 47, 65));
        btnSanPham.setkEndColor(new java.awt.Color(36, 47, 65));
        btnSanPham.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        btnSanPham.setkHoverForeGround(new java.awt.Color(36, 47, 65));
        btnSanPham.setkHoverStartColor(new java.awt.Color(36, 47, 65));
        btnSanPham.setkPressedColor(new java.awt.Color(36, 47, 65));
        btnSanPham.setkSelectedColor(new java.awt.Color(36, 47, 65));
        btnSanPham.setkStartColor(new java.awt.Color(36, 47, 65));
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });

        btnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons-hoadon.png"))); // NOI18N
        btnHoaDon.setText("HOÁ ĐƠN");
        btnHoaDon.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnHoaDon.setkBackGroundColor(new java.awt.Color(36, 47, 65));
        btnHoaDon.setkEndColor(new java.awt.Color(36, 47, 65));
        btnHoaDon.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        btnHoaDon.setkHoverForeGround(new java.awt.Color(36, 47, 65));
        btnHoaDon.setkHoverStartColor(new java.awt.Color(36, 47, 65));
        btnHoaDon.setkPressedColor(new java.awt.Color(36, 47, 65));
        btnHoaDon.setkSelectedColor(new java.awt.Color(36, 47, 65));
        btnHoaDon.setkStartColor(new java.awt.Color(36, 47, 65));
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });

        btnBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons-banhang.png"))); // NOI18N
        btnBanHang.setText("BÁN HÀNG");
        btnBanHang.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnBanHang.setkBackGroundColor(new java.awt.Color(36, 47, 65));
        btnBanHang.setkEndColor(new java.awt.Color(36, 47, 65));
        btnBanHang.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        btnBanHang.setkHoverForeGround(new java.awt.Color(36, 47, 65));
        btnBanHang.setkHoverStartColor(new java.awt.Color(36, 47, 65));
        btnBanHang.setkIndicatorColor(new java.awt.Color(36, 47, 65));
        btnBanHang.setkPressedColor(new java.awt.Color(36, 47, 65));
        btnBanHang.setkSelectedColor(new java.awt.Color(36, 47, 65));
        btnBanHang.setkStartColor(new java.awt.Color(36, 47, 65));
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("APPLE STORE");

        btnVoucher1.setIcon(new javax.swing.ImageIcon("/Users/phamtuyetnga/Desktop/icons-thongke.png")); // NOI18N
        btnVoucher1.setText("THỐNG KÊ");
        btnVoucher1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnVoucher1.setkBackGroundColor(new java.awt.Color(36, 47, 65));
        btnVoucher1.setkEndColor(new java.awt.Color(36, 47, 65));
        btnVoucher1.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        btnVoucher1.setkHoverForeGround(new java.awt.Color(36, 47, 65));
        btnVoucher1.setkHoverStartColor(new java.awt.Color(36, 47, 65));
        btnVoucher1.setkPressedColor(new java.awt.Color(36, 47, 65));
        btnVoucher1.setkSelectedColor(new java.awt.Color(36, 47, 65));
        btnVoucher1.setkStartColor(new java.awt.Color(36, 47, 65));
        btnVoucher1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoucher1ActionPerformed(evt);
            }
        });

        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons-nhanvien.png"))); // NOI18N
        btnNhanVien.setText("NHÂN VIÊN");
        btnNhanVien.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnNhanVien.setkBackGroundColor(new java.awt.Color(36, 47, 65));
        btnNhanVien.setkEndColor(new java.awt.Color(36, 47, 65));
        btnNhanVien.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        btnNhanVien.setkHoverForeGround(new java.awt.Color(36, 47, 65));
        btnNhanVien.setkHoverStartColor(new java.awt.Color(36, 47, 65));
        btnNhanVien.setkPressedColor(new java.awt.Color(36, 47, 65));
        btnNhanVien.setkSelectedColor(new java.awt.Color(36, 47, 65));
        btnNhanVien.setkStartColor(new java.awt.Color(36, 47, 65));
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addComponent(btnKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVoucher1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(btnVoucher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(btnBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoucher1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("APPLE STORE XIN CHÀO");

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/phamtuyetnga/Downloads/NHÓM5.jpg")); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoucherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoucherActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        ViewKhachHang sp = new ViewKhachHang();
        Panel1.removeAll();
        Panel1.add(sp);
        Panel1.setLayout(new FlowLayout());
        this.pack();
        Panel1.setVisible(true);
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        FormNhanVien sp = new FormNhanVien();
        Panel1.removeAll();
        Panel1.add(sp);
        Panel1.setLayout(new FlowLayout());
        this.pack();
        Panel1.setVisible(true);
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        FormSanPham sp = new FormSanPham();
        Panel1.removeAll();
        Panel1.add(sp);
        Panel1.setLayout(new FlowLayout());
        this.pack();
        Panel1.setVisible(true);
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        HoaDonn sp = new HoaDonn();
        Panel1.removeAll();
        Panel1.add(sp);
        Panel1.setLayout(new FlowLayout());
        this.pack();
        Panel1.setVisible(true);
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        FormBanHang sp = new FormBanHang();
        Panel1.removeAll();
        Panel1.add(sp);
        Panel1.setLayout(new FlowLayout());
        this.pack();
        Panel1.setVisible(true);
    }//GEN-LAST:event_btnBanHangActionPerformed

    private void btnVoucher1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoucher1ActionPerformed
        FormThongKe sp = new FormThongKe();
        Panel1.removeAll();
        Panel1.add(sp);
        Panel1.setLayout(new FlowLayout());
        this.pack();
        Panel1.setVisible(true);
    }//GEN-LAST:event_btnVoucher1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private com.k33ptoo.components.KButton btnBanHang;
    private com.k33ptoo.components.KButton btnHoaDon;
    private com.k33ptoo.components.KButton btnKhachHang;
    private com.k33ptoo.components.KButton btnNhanVien;
    private com.k33ptoo.components.KButton btnSanPham;
    private com.k33ptoo.components.KButton btnVoucher;
    private com.k33ptoo.components.KButton btnVoucher1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
