/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author phamtuyetnga
 */
public class FormDkiNV_1 extends javax.swing.JFrame {

    /**
     * Creates new form FormDkiNV
     */
    public FormDkiNV_1() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelKH = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTenDem = new javax.swing.JTextField();
        txtHo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        btnXoa = new javax.swing.JButton();
        txtMaNhanVien = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        rdNghi = new javax.swing.JRadioButton();
        rddiLam = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        txtNgayDiLam = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelKH.setBackground(new java.awt.Color(36, 47, 65));
        PanelKH.setForeground(new java.awt.Color(255, 255, 255));
        PanelKH.setPreferredSize(new java.awt.Dimension(1300, 800));
        PanelKH.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mã Nhân Viên");
        PanelKH.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 80, 86, 27));

        txtTen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PanelKH.add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 147, 192, 27));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tên");
        PanelKH.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 147, 86, 27));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tên Đệm");
        PanelKH.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 214, 86, 27));

        txtTenDem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PanelKH.add(txtTenDem, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 214, 192, 27));

        txtHo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PanelKH.add(txtHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 281, 192, 27));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Họ");
        PanelKH.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 281, 86, 27));

        txtNgaySinh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PanelKH.add(txtNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 348, 192, 27));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ngày Sinh");
        PanelKH.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 348, 80, 27));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Giới Tính");
        PanelKH.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 415, 80, 27));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Địa Chỉ");
        PanelKH.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 80, 86, 27));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Số Điện Thoại");
        PanelKH.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 147, 86, 27));

        txtSoDienThoai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PanelKH.add(txtSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 147, 192, 27));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Email");
        PanelKH.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 214, 86, 27));

        rdNam.setBackground(new java.awt.Color(97, 212, 195));
        buttonGroup1.add(rdNam);
        rdNam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdNam.setForeground(new java.awt.Color(255, 255, 255));
        rdNam.setText("Nam");
        PanelKH.add(rdNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 416, 83, -1));

        rdNu.setBackground(new java.awt.Color(97, 212, 195));
        buttonGroup1.add(rdNu);
        rdNu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdNu.setForeground(new java.awt.Color(255, 255, 255));
        rdNu.setText("Nữ");
        PanelKH.add(rdNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 416, 80, -1));

        btnXoa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setText("ĐĂNG KÍ");
        btnXoa.setPreferredSize(new java.awt.Dimension(100, 30));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        PanelKH.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 630, 141, 60));
        PanelKH.add(txtMaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 80, 192, 27));
        PanelKH.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 80, 192, 27));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Mật Khẩu");
        PanelKH.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 281, 91, 29));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Chức Vụ");
        PanelKH.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 488, 80, 29));

        jComboBox1.setBackground(new java.awt.Color(97, 212, 195));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PanelKH.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 489, 189, 29));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PanelKH.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 214, 192, 27));

        txtMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PanelKH.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 282, 192, 27));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Ghi Chú");
        PanelKH.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 488, 88, 29));

        txtGhiChu.setColumns(20);
        txtGhiChu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtGhiChu.setRows(5);
        jScrollPane1.setViewportView(txtGhiChu);

        PanelKH.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 488, 192, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Trạng Thái");
        PanelKH.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 350, 91, 29));

        rdNghi.setBackground(new java.awt.Color(97, 212, 195));
        rdNghi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdNghi.setForeground(new java.awt.Color(255, 255, 255));
        rdNghi.setText("Nghỉ ");
        PanelKH.add(rdNghi, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 352, -1, -1));

        rddiLam.setBackground(new java.awt.Color(97, 212, 195));
        rddiLam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rddiLam.setForeground(new java.awt.Color(255, 255, 255));
        rddiLam.setText("Đi Làm");
        rddiLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rddiLamActionPerformed(evt);
            }
        });
        PanelKH.add(rddiLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 352, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ngày Đi Làm");
        PanelKH.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 419, 91, 29));

        txtNgayDiLam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PanelKH.add(txtNgayDiLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 420, 192, 27));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ĐĂNG KÝ NHÂN VIÊN");
        PanelKH.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 380, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png"))); // NOI18N
        PanelKH.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 80));

        jLabel3.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("APPLE STORE");
        PanelKH.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 140, 60));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dt.png"))); // NOI18N
        PanelKH.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 590, 190, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PanelKH, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rddiLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rddiLamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rddiLamActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        new Login1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDkiNV_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDkiNV_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDkiNV_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDkiNV_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDkiNV_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelKH;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNghi;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JRadioButton rddiLam;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtNgayDiLam;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenDem;
    // End of variables declaration//GEN-END:variables
}
